# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

on:
  - pull_request
  - push

name: "Continuous Integration"

jobs:
  validate:
    name: "Validate"

    runs-on: "ubuntu-latest"

    strategy:
      fail-fast: false
      matrix:
        php-versions:
          - "7.1"

        dependencies:
          - ""

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-versions }}"
          extensions: "json" #optional
          ini-values: "opcache.enable=1, opcache.enable_cli=1, zend.assertions=1, assert.exception=On" #optional
          coverage: "none" #optional

      - name: "Validate composer.json"
        run: "composer validate --strict"

      - name: "Determine composer cache directory"
        id: "determine-composer-cache-directory"
        run: "echo \"::set-output name=directory::$(composer config cache-dir)\""

      - name: "Cache dependencies installed with composer"
        uses: "actions/cache@v1"
        with:
          path: "${{ steps.determine-composer-cache-directory.outputs.directory }}"
          key: "php-${{ matrix.php-versions }}-composer-${{ matrix.dependencies }}-${{ hashFiles('composer.lock') }}"
          restore-keys: "php-${{ matrix.php-versions }}-composer-${{ matrix.dependencies }}-"

      - name: "Update dependencies with composer"
        run: "composer update --optimize-autoloader --prefer-dist --prefer-stable --no-progress --no-interaction --no-suggest -vv ${{ matrix.dependencies }}"

      - name: "Run composer-normalize"
        run: "composer normalize --dry-run"

  install:
    name: "Check dependencies"

    needs: "validate"

    runs-on: "ubuntu-latest"

    strategy:
      fail-fast: false
      matrix:
        php-versions:
          - "7.1"
          - "7.2"
          - "7.3"
          - "7.4"
#          - "8.0"

        dependencies:
          - "--prefer-lowest"
          - ""

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-versions }}"
          extensions: "json" #optional
          ini-values: "opcache.enable=1, opcache.enable_cli=1, zend.assertions=1, assert.exception=On" #optional
          coverage: "none" #optional

      - name: "Determine composer cache directory"
        id: "determine-composer-cache-directory"
        run: "echo \"::set-output name=directory::$(composer config cache-dir)\""

      - name: "Cache dependencies installed with composer"
        uses: "actions/cache@v1"
        with:
          path: "${{ steps.determine-composer-cache-directory.outputs.directory }}"
          key: "php-${{ matrix.php-versions }}-composer-${{ matrix.dependencies }}-${{ hashFiles('composer.lock') }}"
          restore-keys: "php-${{ matrix.php-versions }}-composer-${{ matrix.dependencies }}-"

      - name: "Update dependencies with composer"
        run: "composer update --optimize-autoloader --prefer-dist --prefer-stable --no-progress --no-interaction --no-suggest -vv ${{ matrix.dependencies }}"

      - name: "Check dependencies with composer"
        run: "composer outdated --direct --strict"

  coding-standards:
    name: "Coding Standards"

    needs: "install"

    runs-on: "ubuntu-latest"

    strategy:
      fail-fast: false
      matrix:
        php-versions:
          - "7.1"

        dependencies:
          - ""

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-versions }}"
          extensions: "json" #optional
          ini-values: "opcache.enable=1, opcache.enable_cli=1, zend.assertions=1, assert.exception=On" #optional
          coverage: "none" #optional

      - name: "Determine composer cache directory"
        id: "determine-composer-cache-directory"
        run: "echo \"::set-output name=directory::$(composer config cache-dir)\""

      - name: "Cache dependencies installed with composer"
        uses: "actions/cache@v1"
        with:
          path: "${{ steps.determine-composer-cache-directory.outputs.directory }}"
          key: "php-${{ matrix.php-versions }}-composer-${{ matrix.dependencies }}-${{ hashFiles('composer.lock') }}"
          restore-keys: "php-${{ matrix.php-versions }}-composer-${{ matrix.dependencies }}-"

      - name: "Update dependencies with composer"
        run: "composer update --optimize-autoloader --prefer-dist --prefer-stable --no-progress --no-interaction --no-suggest -vv ${{ matrix.dependencies }}"

      - name: "Run friendsofphp/php-cs-fixer"
        run: "vendor/bin/php-cs-fixer fix --dry-run -vv"

      - name: "Run squizlabs/php_codesniffer"
        run: "vendor/bin/phpcs --colors"

  static-code-analysis:
    name: "Static Code Analysis"

    needs: "install"

    runs-on: "ubuntu-latest"

    strategy:
      fail-fast: false
      matrix:
        php-versions:
          - "7.1"

        dependencies:
          - ""

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-versions }}"
          extensions: "json" #optional
          ini-values: "opcache.enable=1, opcache.enable_cli=1, zend.assertions=1, assert.exception=On" #optional
          coverage: "none" #optional

      - name: "Determine composer cache directory"
        id: "determine-composer-cache-directory"
        run: "echo \"::set-output name=directory::$(composer config cache-dir)\""

      - name: "Cache dependencies installed with composer"
        uses: "actions/cache@v1"
        with:
          path: "${{ steps.determine-composer-cache-directory.outputs.directory }}"
          key: "php-${{ matrix.php-versions }}-composer-${{ matrix.dependencies }}-${{ hashFiles('composer.lock') }}"
          restore-keys: "php-${{ matrix.php-versions }}-composer-${{ matrix.dependencies }}-"

      - name: "Update dependencies with composer"
        run: "composer update --optimize-autoloader --prefer-dist --prefer-stable --no-progress --no-interaction --no-suggest -vv ${{ matrix.dependencies }}"

      - name: "Run phpstan/phpstan"
        run: "vendor/bin/phpstan analyse -c phpstan.neon --memory-limit=768M --no-progress"

  tests:
    name: "UnitTests"

    needs:
      - "coding-standards"
      - "static-code-analysis"

    runs-on: "ubuntu-latest"

    strategy:
      fail-fast: false
      matrix:
        php-versions:
          - "7.1"

        dependencies:
          - ""

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-versions }}"
          extensions: "json" #optional
          ini-values: "opcache.enable=1, opcache.enable_cli=1, zend.assertions=1, assert.exception=On" #optional
          coverage: "none" #optional

      - name: "Determine composer cache directory"
        id: "determine-composer-cache-directory"
        run: "echo \"::set-output name=directory::$(composer config cache-dir)\""

      - name: "Cache dependencies installed with composer"
        uses: "actions/cache@v1"
        with:
          path: "${{ steps.determine-composer-cache-directory.outputs.directory }}"
          key: "php-${{ matrix.php-versions }}-composer-${{ matrix.dependencies }}-${{ hashFiles('composer.lock') }}"
          restore-keys: "php-${{ matrix.php-versions }}-composer-${{ matrix.dependencies }}-"

      - name: "Update dependencies with composer"
        run: "composer update --optimize-autoloader --prefer-dist --prefer-stable --no-progress --no-interaction --no-suggest -vv ${{ matrix.dependencies }}"

      - name: "Run unit tests with phpunit/phpunit"
        run: "vendor/bin/phpunit -c phpunit.xml --colors --no-coverage"

  code-coverage:
    name: "Code Coverage"

    needs: "tests"

    runs-on: "ubuntu-latest"

    strategy:
      fail-fast: false
      matrix:
        php-versions:
          - "7.1"

        dependencies:
          - ""

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-versions }}"
          extensions: "json" #optional
          ini-values: "opcache.enable=1, opcache.enable_cli=1, zend.assertions=1, assert.exception=On" #optional
          coverage: "xdebug" #optional

      - name: "Determine composer cache directory"
        id: "determine-composer-cache-directory"
        run: "echo \"::set-output name=directory::$(composer config cache-dir)\""

      - name: "Cache dependencies installed with composer"
        uses: "actions/cache@v1"
        with:
          path: "${{ steps.determine-composer-cache-directory.outputs.directory }}"
          key: "php-${{ matrix.php-versions }}-composer-${{ matrix.dependencies }}-${{ hashFiles('composer.lock') }}"
          restore-keys: "php-${{ matrix.php-versions }}-composer-${{ matrix.dependencies }}-"

      - name: "Update dependencies with composer"
        run: "composer update --optimize-autoloader --prefer-dist --prefer-stable --no-progress --no-interaction --no-suggest -vv ${{ matrix.dependencies }}"

      - name: "Create cache directory for phpunit/phpunit"
        run: "mkdir -p .build/coverage"

      - name: "Collect code coverage with Xdebug and phpunit/phpunit"
        run: "vendor/bin/phpunit -c phpunit.xml --colors --coverage-clover=clover.xml --coverage-text --coverage-xml=.build/coverage/coverage-xml --log-junit=.build/coverage/junit.xml"

      - name: "Upload coverage to Codecov"
        uses: "codecov/codecov-action@master"
        with:
          token: "${{secrets.CODECOV_TOKEN}}"
          file: "clover.xml"
          flags: "phpunit"

#      - name: "Run mutation tests with infection/infection"
#        run: "vendor/bin/infection --min-covered-msi=95 --min-msi=95 --coverage=.build/coverage"

#  merge:
#    name: "Merge"
#
#    runs-on: "ubuntu-latest"
#
#    strategy:
#      fail-fast: false
#      matrix:
#        php-versions:
#          - "7.1"
#
#        dependencies:
#          - ""
#
#    needs:
#      - "code-coverage"
#      - "tests"
#
#    if: >
#      github.event_name == 'pull_request' &&
#      github.event.pull_request.draft == false && (
#        github.event.action == 'opened' ||
#        github.event.action == 'reopened' ||
#        github.event.action == 'synchronize'
#      ) && (
#        (github.actor == 'dependabot-preview[bot]' && startsWith(github.event.pull_request.title, 'Build(deps-dev)')) ||
#        (github.actor == 'mimmi20' && github.event.pull_request.title == 'Enhancement: Update license year')
#      )
#
#    steps:
#      - name: "Request review from @mimmi20"
#        uses: "actions/github-script@0.8.0"
#        with:
#          github-token: "${{ secrets.MERGE_TOKEN }}"
#          script: |
#            const pullRequest = context.payload.pull_request
#            const repository = context.repo
#
#            const reviewers = [
#              "mimmi20",
#            ]
#
#            await github.pulls.createReviewRequest({
#              owner: repository.owner,
#              pull_number: pullRequest.number,
#              repo: repository.repo,
#              reviewers: reviewers,
#            })
#
#      - name: "Assign @mimmi20"
#        uses: "actions/github-script@0.8.0"
#        with:
#          github-token: "${{ secrets.MERGE_TOKEN }}"
#          script: |
#            const pullRequest = context.payload.pull_request
#            const repository = context.repo
#
#            const reviewers = [
#              "mimmi20",
#            ]
#
#            await github.issues.addAssignees({
#              assignees: reviewers,
#              issue_number: pullRequest.number,
#              owner: repository.owner,
#              repo: repository.repo,
#            })
#
#      - name: "Approve pull request"
#        uses: "actions/github-script@0.8.0"
#        if: "github.actor != 'mimmi20'"
#        with:
#          github-token: "${{ secrets.MERGE_TOKEN }}"
#          script: |
#            const pullRequest = context.payload.pull_request
#            const repository = context.repo
#
#            await github.pulls.createReview({
#              event: "APPROVE",
#              owner: repository.owner,
#              pull_number: pullRequest.number,
#              repo: repository.repo,
#            })
#
#      - name: "Merge pull request"
#        uses: "actions/github-script@0.8.0"
#        with:
#          github-token: "${{ secrets.MERGE_TOKEN }}"
#          script: |
#            const pullRequest = context.payload.pull_request
#            const repository = context.repo
#
#            await github.pulls.merge({
#              merge_method: "merge",
#              owner: repository.owner,
#              pull_number: pullRequest.number,
#              repo: repository.repo,
#            })
